name: image_gallery_saver_example
version: 2.0.3+3
publish_to: none
description: Demonstrates how to use the image_gallery_saver plugin.
environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  fluttertoast: ^8.2.5
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  image_gallery_saver:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
